sudo: required
services:
  -docker

before_install:
  - docker build -t renovatiodoc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run renovatiodoc/react-test npm test -- --coverage

after_success:
  - docker build -t renovatiodoc/multi-client ./client
  - docker build -t renovatiodoc/multi-nginx ./nginx
  - docker build -t renovatiodoc/multi-server ./server
  - docker build -t renovatiodoc/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub.
  - docker push renovatiodoc/multi-client
  - docker push renovatiodoc/multi-nginx
  - docker push renovatiodoc/multi-server
  - docker push renovatiodoc/multi-worker
